// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuetwwdfqellisyxpivr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZXR3d2RmcWVsbGlzeXhwaXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQyOTcsImV4cCI6MjA2NTUwMDI5N30.AgHBTCAlehgvgBW5YvXzPjFQZtx6RtUp518WdjGZHU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);